name: demo action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: run command
        run: echo "hello world"

      - name: run commands 2
        run: echo "hi"
