name: demo action
on:
 push:  
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: run command
     run: echo "hello world"
	 
   - name: run commands 2 
     run: echo "hi"
	 
   - uses: actions/checkout@v4
  
